const agents = [
  ['Jett','DUELIST','Rüzgâr gibi hareket eder ve hassas saldırılarla alan açar.'],['Phoenix','DUELIST','Alevleriyle savaşır, görüşü böler ve kendini iyileştirir.'],['Raze','DUELIST','Patlayıcılarıyla alan açar ve rakipleri baskılar.'],['Reyna','DUELIST','Düşmanlarını alt ederek güçlenen agresif bir düellocu.'],['Yoru','DUELIST','Boyutlar arası geçişlerle rakibi şaşırtır.'],['Neon','DUELIST','Elektrik hızında koşarak ani baskınlar yapar.'],['Iso','DUELIST','Enerji bariyerleriyle düelloları kendi lehine çevirir.'],['Waylay','DUELIST','Hareket kabiliyetiyle rakip savunmasını parçalar.'],
  ['Brimstone','CONTROLLER','Uydu destekli yetenekleriyle alanı ve görüşü kontrol eder.'],['Viper','CONTROLLER','Zehir perdeleriyle görüşü ve bölgeyi yönetir.'],['Omen','CONTROLLER','Gölgeden hareket eder, görüşü bozar ve ışınlanır.'],['Astra','CONTROLLER','Kozmik yıldızlarıyla haritanın farklı noktalarına hükmeder.'],['Harbor','CONTROLLER','Suyla bariyerler kurarak takımına güvenli geçiş sağlar.'],['Clove','CONTROLLER','Ölümün ötesinden bile takımını desteklemeye devam eder.'],['Miks','CONTROLLER','Alan kontrolü ve takım desteğiyle round temposunu değiştirir.'],
  ['Sova','INITIATOR','Keşif oklarıyla düşman konumlarını açığa çıkarır.'],['Breach','INITIATOR','Duvarların içinden sarsıcı saldırılar gönderir.'],['Skye','INITIATOR','Doğayla kurduğu bağ sayesinde iz sürer ve iyileştirir.'],['KAY/O','INITIATOR','Düşman yeteneklerini bastıran savaş makinesidir.'],['Fade','INITIATOR','Kabusları kullanarak düşmanların izini sürer.'],['Gekko','INITIATOR','Küçük dostlarıyla alanı temizler ve spike yönetir.'],['Tejo','INITIATOR','Uzaktan yönlendirdiği patlayıcılarla savunmayı çözer.'],
  ['Sage','SENTINEL','İyileştirme ve bariyerleriyle takımını korur.'],['Cypher','SENTINEL','Kameraları ve tuzaklarıyla bilgi toplar.'],['Killjoy','SENTINEL','Cihazlarıyla bölgeyi güvence altına alır.'],['Chamber','SENTINEL','Özel silahları ve ışınlanmasıyla kritik açıları tutar.'],['Deadlock','SENTINEL','Nanotel bariyerleriyle rakip hareketlerini kısıtlar.'],['Vyse','SENTINEL','Metal dikenleriyle rakipleri ayırır ve tuzağa düşürür.'],['Veto','SENTINEL','Rakip yeteneklerini kendi lehine etkisizleştirir.']
].map(([name, role, desc]) => ({ name, role, desc, abilities: [['Q YETENEĞİ','Rolüne uygun alan kontrolü ve takım desteği sağlar.'],['E YETENEĞİ','Round içinde konum avantajı yaratır.'],['ULTİ','Doğru zamanda kullanıldığında takımın planını güçlendirir.']] }));

const weapons = [
  ['Classic','TABANCA','Ücretsiz','Hafif ve güvenilir'],['Shorty','TABANCA','300','Yakın mesafede güçlü'],['Frenzy','TABANCA','450','Otomatik seri atış'],['Ghost','TABANCA','500','Sessiz ve hassas'],['Sheriff','TABANCA','800','Yüksek hasarlı revolver'],['Bandit','TABANCA','600','Dengeli hafif tabanca'],
  ['Stinger','SMG','1.100','Yakın mesafe baskısı'],['Spectre','SMG','1.600','Dengeli otomatik silah'],['Bulldog','TÜFEK','2.050','Ekonomik saldırı tüfeği'],['Guardian','TÜFEK','2.250','Tek atış hassasiyeti'],['Phantom','TÜFEK','2.900','Kontrollü otomatik tüfek'],['Vandal','TÜFEK','2.900','Güçlü tek atış hasarı'],
  ['Bucky','SHOTGUN','850','Yakın mesafe yıkımı'],['Judge','SHOTGUN','1.850','Hızlı pompalı baskı'],['Marshal','SNIPER','950','Hafif keskin nişancı'],['Operator','SNIPER','4.700','Yüksek hasar'],['Ares','AĞIR','1.600','Yüksek mermi kapasitesi'],['Odin','AĞIR','3.200','Baskı için ağır makineli'],['Bıçak','YAKIN DÖVÜŞ','Ücretsiz','Her zaman yanında'],['Warden','ÖZEL','2.900','Warden silahı / özel ekipman']
].map(([name, category, price, desc]) => ({ name, category, price, desc }));

const maps = [['Ascent','İtalya','Orta alan kontrolü ve iki kapılı site düzeni.'],['Bind','Fas','Tek yönlü ışınlanmalarla hızlı rotalar.'],['Haven','Bhutan','Üç bomba alanı, yüksek tempolu kararlar.'],['Icebox','Rusya','Dikey oyun ve zipline rotaları.'],['Lotus','Hindistan','Üç alan ve döner kapılar.'],['Sunset','Los Angeles','Dar sokaklar ve kritik orta alan.']].map(([name, region, desc]) => ({ name, region, desc }));
const $ = s => document.querySelector(s); const app = $('#app');
function layout(title, sub, content) { return `<section class="page"><div class="container"><div class="page-head"><p class="eyebrow">VANTA // DOSYA ${title}</p><h1>${title}</h1><p>${sub}</p></div>${content}</div></section>`; }
function home() { return `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Bağımsız taktik rehber // 2026</p><h1>Own the<br><em>unknown.</em></h1><p>Haritanı oku. Ajanını seç. Her round’da kendi planını uygula. Rekabetçi FPS deneyimin için sade ve hızlı bir keşif alanı.</p><div class="actions"><a class="button primary" href="#/agents">Ajanları keşfet</a><a class="button ghost" href="#/weapons">Silahları incele</a></div></div><div class="hero-art"><div class="agent-silhouette">V</div><span class="art-label">NO OFFICIAL AFFILIATION</span></div></div></section><section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Kontrol sende</p><h2>Oyunu kendi<br>ritminle oyna.</h2></div><p>29 ajan, 20 ekipman ve farklı oyun stilleri. VANTA; karar vermen için hızlı ve sade bir keşif alanı sunar.</p></div><div class="feature-grid"><article class="feature-card"><span class="feature-index">01 // AGENTS</span><h3>Rolünü seç</h3><p>Tüm ajanların rollerini ve yetenek özetlerini keşfet.</p></article><article class="feature-card"><span class="feature-index">02 // LOADOUT</span><h3>Donanımını kur</h3><p>Her ekipmanın kategorisini, fiyatını ve kullanım amacını karşılaştır.</p></article><article class="feature-card"><span class="feature-index">03 // MAPS</span><h3>Haritayı oku</h3><p>Alan düzenlerini anlayarak her round için daha iyi bir plan oluştur.</p></article></div></div></section>`; }
function agentCards(list) { return list.length ? list.map(a => `<article class="data-card" data-agent="${a.name}"><div class="card-art"><strong>${a.name[0]}</strong></div><div class="card-body"><span class="role">${a.role}</span><h3>${a.name}</h3><p>${a.desc}</p></div></article>`).join('') : `<div class="empty-state">Aramana uygun ajan bulunamadı.</div>`; }
function agentsPage() { return layout('Ajanlar',`Tüm ${agents.length} ajanı rolüne göre filtrele, ara ve detaylarını incele.`, `<div class="filters"><input class="search" id="agent-search" placeholder="Ajan ara..."/><button class="filter-btn active" data-role="ALL">TÜMÜ (${agents.length})</button>${['DUELIST','INITIATOR','CONTROLLER','SENTINEL'].map(r => `<button class="filter-btn" data-role="${r}">${r}</button>`).join('')}</div><div class="card-grid" id="agent-grid">${agentCards(agents)}</div>`); }
function weaponCards(list) { return list.length ? list.map(w => `<article class="data-card weapon-card"><div class="card-art"><strong>${w.name[0]}</strong></div><div class="card-body"><span class="role">${w.category}</span><h3>${w.name}</h3><div class="weapon-meta"><span>${w.desc}</span><b class="price">${w.price} CR</b></div></div></article>`).join('') : `<div class="empty-state">Silah bulunamadı.</div>`; }
function weaponsPage() { const categories = ['TABANCA','SMG','TÜFEK','SNIPER','SHOTGUN','AĞIR','YAKIN DÖVÜŞ','ÖZEL']; return layout('Silahlar',`Tüm ${weapons.length} ekipmanı kategoriye göre filtrele ve ekonomini planla.`, `<div class="filters"><input class="search" id="weapon-search" placeholder="Silah ara..."/><select class="select" id="weapon-filter"><option value="ALL">TÜM KATEGORİLER</option>${categories.map(c => `<option>${c}</option>`).join('')}</select></div><div class="card-grid" id="weapon-grid">${weaponCards(weapons)}</div>`); }
function mapsPage() { return layout('Haritalar','Her haritanın kendine özgü ritmi vardır. Alan düzenini öğren, rotanı takımınla paylaş.', `<div class="map-grid">${maps.map(m => `<article class="map-card"><span class="role">${m.region}</span><h3>${m.name}</h3><p>${m.desc}</p></article>`).join('')}</div>`); }
function statsPage() { return layout('İstatistikler','Riot API bağlantısı aktif değildir. Sahte istatistik göstermiyor, gerçek entegrasyon için güvenli form iskeleti sunuyoruz.', `<div class="stats-layout"><form class="stat-panel" id="stats-form"><h3>Oyuncu sorgula</h3><label for="riot-id">Riot ID</label><input id="riot-id" placeholder="OyuncuAdı" required><label for="tag">Tagline</label><input id="tag" placeholder="TR1" required><button class="button primary" style="width:100%;margin-top:20px">API bağlantısını başlat</button><div class="api-note">API anahtarını tarayıcıya gömme. Üretimde sunucu tarafında <code>/api/player</code> proxy endpoint’i oluştur.</div></form><div class="stat-panel"><p class="eyebrow">Entegrasyon alanı</p><h3>Verilerin burada görünecek.</h3><p style="color:var(--muted)">Gerçek API bağlantısı kurulmadığı için sahte istatistik göstermiyoruz. Form Riot ID ve tagline değerlerini backend’e göndermeye hazırdır.</p></div></div>`); }
function aboutPage() { return layout('Hakkında','VANTA, VALORANT atmosferinden ilham alan bağımsız bir arayüz konseptidir.', `<div class="stat-panel"><p>Bu proje Riot Games’in resmi sitesi değildir ve Riot Games logolarını veya resmi görsellerini kullanmaz. Marka isimleri ilgili sahiplerinin mülkiyetindedir.</p><p style="color:var(--muted)">Ajan ve ekipman listeleri bilgilendirme amaçlıdır; oyun güncellemeleriyle değişebilir.</p></div>`); }
function notFound() { return `<section class="not-found container"><p class="eyebrow">ERROR // 404</p><h1>BU SAYFA KAYIP.</h1><p style="color:var(--muted)">Aradığın rota bulunamadı.</p><a class="button primary" href="#/">Ana sayfaya dön</a></section>`; }
function openAgent(name) { const a = agents.find(x => x.name === name); $('#modal-root').innerHTML = `<div class="modal-backdrop"><article class="modal"><button class="modal-close" aria-label="Kapat">×</button><span class="role">${a.role}</span><h2>${a.name}</h2><p style="color:var(--muted)">${a.desc}</p>${a.abilities.map(x => `<div class="ability"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</article></div>`; $('.modal-close').onclick = () => $('#modal-root').innerHTML = ''; $('.modal-backdrop').onclick = e => { if (e.target.classList.contains('modal-backdrop')) $('#modal-root').innerHTML = ''; }; }
function bind() { document.querySelectorAll('[data-route-link]').forEach(a => a.classList.toggle('active', a.getAttribute('href') === location.hash)); document.querySelectorAll('.data-card[data-agent]').forEach(c => c.onclick = () => openAgent(c.dataset.agent)); const as = $('#agent-search'); if (as) { let role = 'ALL'; const render = () => { const q = as.value.toLowerCase(); $('#agent-grid').innerHTML = agentCards(agents.filter(a => (role === 'ALL' || a.role === role) && a.name.toLowerCase().includes(q))); }; as.oninput = render; document.querySelectorAll('[data-role]').forEach(b => b.onclick = () => { role = b.dataset.role; document.querySelectorAll('[data-role]').forEach(x => x.classList.remove('active')); b.classList.add('active'); render(); }); } const ws = $('#weapon-search'); if (ws) { const wf = $('#weapon-filter'); const render = () => $('#weapon-grid').innerHTML = weaponCards(weapons.filter(w => (wf.value === 'ALL' || w.category === wf.value) && w.name.toLowerCase().includes(ws.value.toLowerCase()))); ws.oninput = render; wf.onchange = render; } const form = $('#stats-form'); if (form) form.onsubmit = e => { e.preventDefault(); alert('API endpoint hazır değil. Gerçek veri göstermek için backend bağlantısını tamamlayın.'); }; }
function render() { const route = location.hash.replace('#/', '').split('/')[0]; const pages = { agents: agentsPage, weapons: weaponsPage, maps: mapsPage, stats: statsPage, about: aboutPage }; app.innerHTML = route ? pages[route] ? pages[route]() : notFound() : home(); bind(); window.scrollTo(0, 0); }
$('#theme-toggle').onclick = () => { document.documentElement.dataset.theme = document.documentElement.dataset.theme === 'light' ? '' : 'light'; localStorage.setItem('vanta-theme', document.documentElement.dataset.theme); }; if (localStorage.getItem('vanta-theme')) document.documentElement.dataset.theme = 'light'; $('.nav-toggle').onclick = () => { $('.nav-menu').classList.toggle('open'); $('.nav-toggle').setAttribute('aria-expanded', $('.nav-menu').classList.contains('open')); }; window.addEventListener('hashchange', () => { $('.nav-menu').classList.remove('open'); render(); }); window.addEventListener('load', () => { setTimeout(() => { $('#loader').classList.add('done'); document.body.style.overflowY = 'auto'; }, 450); render(); });
