const agents=[
 {name:'Jett',role:'DUELIST',desc:'Hız ve hassasiyetle savaş alanını keser.',abilities:[['CLOUD Burst','Görüşü kısa süreliğine engelleyen bir bulut fırlatır.'],['UPDRAFT','Jett’i yukarı doğru iter.'],['TAILWIND','Hareket yönünde hızla atılır.']]},
 {name:'Sova',role:'INITIATOR',desc:'Bilgi toplayarak takımına üstünlük sağlar.',abilities:[['RECON BOLT','Düşmanları ortaya çıkaran bir ok fırlatır.'],['SHOCK BOLT','Patlayıcı bir ok ile alanı kontrol eder.'],['HUNTER’S FURY','Harita boyunca enerji darbeleri gönderir.']]},
 {name:'Sage',role:'SENTINEL',desc:'İyileştirme ve bariyerleriyle takımını korur.',abilities:[['BARRIER ORB','Geçilemez bir duvar oluşturur.'],['SLOW ORB','Yavaşlatan bir alan yaratır.'],['HEALING ORB','Bir müttefiki veya kendini iyileştirir.']]},
 {name:'Omen',role:'CONTROLLER',desc:'Gölgeden hareket eder, görüşü ve alanı bozar.',abilities:[['SHROUDED STEP','Kısa menzilli ışınlanma yapar.'],['DARK COVER','Görüşü engelleyen karanlık bir küre bırakır.'],['PARANOIA','Oyuncuları kör eden bir enerji gönderir.']]},
 {name:'Raze',role:'DUELIST',desc:'Patlayıcılarıyla alan açar ve baskı kurar.',abilities:[['BOOM BOT','Düşman arayan bir bot gönderir.'],['PAINT SHELLS','Parçacık bombası fırlatır.'],['SHOWSTOPPER','Yıkıcı bir roketatar kuşanır.']]},
 {name:'Killjoy',role:'SENTINEL',desc:'Cihazlarıyla bölgeyi güvence altına alır.',abilities:[['ALARM BOT','Yakındaki düşmanları avlar.'],['TURRET','Otomatik ateş eden bir taret yerleştirir.'],['LOCKDOWN','Bölgedeki düşmanları etkisiz bırakır.']]}
];
const weapons=[['Classic','TABANCA','Ücretsiz','Hafif ve güvenilir'],['Stinger','SMG','1.100','Yakın mesafe baskısı'],['Vandal','TÜFEK','2.900','Tek atış hassasiyeti'],['Operator','SNIPER','4.700','Yüksek hasar'],['Bucky','SHOTGUN','850','Yakın mesafe yıkımı'],['Odin','AĞIR','3.200','Yüksek mermi kapasitesi'],['Ghost','TABANCA','500','Sessiz ve hassas'],['Spectre','SMG','1.600','Dengeli otomatik']].map(([name,category,price,desc])=>({name,category,price,desc}));
const maps=[['Ascent','İtalya','Orta alan kontrolü ve iki kapılı site düzeni.'],['Bind','Fas','Tek yönlü ışınlanmalarla hızlı rotalar.'],['Haven','Bhutan','Üç bomba alanı, yüksek tempolu kararlar.'],['Icebox','Rusya','Dikey oyun ve zipline rotaları.'],['Lotus','Hindistan','Üç alan ve döner kapılar.'],['Sunset','Los Angeles','Dar sokaklar ve kritik orta alan.']].map(([name,region,desc])=>({name,region,desc}));
const $=s=>document.querySelector(s); const app=$('#app');
function layout(title,sub,content){return `<section class="page"><div class="container"><div class="page-head"><p class="eyebrow">VANTA // DOSYA ${title}</p><h1>${title}</h1><p>${sub}</p></div>${content}</div></section>`}
function home(){return `<section class="hero"><div class="container hero-grid"><div class="hero-copy"><p class="eyebrow">Bağımsız taktik rehber // 2024</p><h1>Own the<br><em>unknown.</em></h1><p>Haritanı oku. Ajanını seç. Her round’da kendi planını uygula. Rekabetçi FPS deneyimin için sade ve hızlı bir keşif alanı.</p><div class="actions"><a class="button primary" href="#/agents">Ajanları keşfet</a><a class="button ghost" href="#/weapons">Silahları incele</a></div></div><div class="hero-art"><div class="agent-silhouette">V</div><span class="art-label">NO OFFICIAL AFFILIATION</span></div></div></section><section class="section"><div class="container"><div class="section-head"><div><p class="eyebrow">Kontrol sende</p><h2>Oyunu kendi<br>ritminle oyna.</h2></div><p>Bilgi, refleks ve takım iletişimi. VANTA; ajanlar, silahlar ve haritalar hakkında hızlıca karar vermene yardımcı olur.</p></div><div class="feature-grid"><article class="feature-card"><span class="feature-index">01 // AGENTS</span><h3>Rolünü seç</h3><p>Her rolün güçlü ve zayıf yönlerini keşfet, oyun tarzına en uygun ajanı bul.</p></article><article class="feature-card"><span class="feature-index">02 // LOADOUT</span><h3>Donanımını kur</h3><p>Ekonomini yönet, silahların fiyat ve temel özelliklerini tek bakışta gör.</p></article><article class="feature-card"><span class="feature-index">03 // MAPS</span><h3>Haritayı oku</h3><p>Alan düzenlerini anlayarak her round için daha iyi bir plan oluştur.</p></article></div></div></section>`}
function agentsPage(){return layout('Ajanlar','Her ajan farklı bir yaklaşım sunar. Rolüne göre filtrele, detayları incele ve sıradaki seçimini yap.',`<div class="filters"><input class="search" id="agent-search" placeholder="Ajan ara..."/><button class="filter-btn active" data-role="ALL">TÜMÜ</button>${['DUELIST','INITIATOR','CONTROLLER','SENTINEL'].map(r=>`<button class="filter-btn" data-role="${r}">${r}</button>`).join('')}</div><div class="card-grid" id="agent-grid">${agentCards(agents)}</div>`)}
function agentCards(list){return list.length?list.map(a=>`<article class="data-card" data-agent="${a.name}"><div class="card-art"><strong>${a.name[0]}</strong></div><div class="card-body"><span class="role">${a.role}</span><h3>${a.name}</h3><p>${a.desc}</p></div></article>`).join(''):`<div class="empty-state">Aramana uygun ajan bulunamadı.</div>`}
function weaponsPage(){return layout('Silahlar','Ekonomini yönet. Kategori seç, temel bilgileri karşılaştır ve round planını buna göre kur.',`<div class="filters"><input class="search" id="weapon-search" placeholder="Silah ara..."/><select class="select" id="weapon-filter"><option value="ALL">TÜM KATEGORİLER</option>${['TABANCA','SMG','TÜFEK','SNIPER','SHOTGUN','AĞIR'].map(c=>`<option>${c}</option>`).join('')}</select></div><div class="card-grid" id="weapon-grid">${weaponCards(weapons)}</div>`)}
function weaponCards(list){return list.length?list.map(w=>`<article class="data-card weapon-card"><div class="card-art"><strong>${w.name[0]}</strong></div><div class="card-body"><span class="role">${w.category}</span><h3>${w.name}</h3><div class="weapon-meta"><span>${w.desc}</span><b class="price">${w.price} CR</b></div></div></article>`).join(''):`<div class="empty-state">Silah bulunamadı.</div>`}
function mapsPage(){return layout('Haritalar','Her haritanın kendine özgü ritmi vardır. Alan düzenini öğren, rotanı takımınla paylaş.',`<div class="filters">${['TÜMÜ','3 ALAN','DİĞER'].map((x,i)=>`<button class="filter-btn ${i?'':'active'}">${x}</button>`).join('')}</div><div class="map-grid">${maps.map(m=>`<article class="map-card"><span class="role">${m.region}</span><h3>${m.name}</h3><p>${m.desc}</p></article>`).join('')}</div>`)}
function statsPage(){return layout('İstatistikler','Riot API bağlantısı bu bağımsız arayüzde aktif değildir. Riot ID alanını hazır entegrasyon akışıyla kullanabilirsin.',`<div class="stats-layout"><form class="stat-panel" id="stats-form"><h3>Oyuncu sorgula</h3><label for="riot-id">Riot ID</label><input id="riot-id" placeholder="OyuncuAdı" required><label for="tag">Tagline</label><input id="tag" placeholder="TR1" required><button class="button primary" style="width:100%;margin-top:20px">API bağlantısını başlat</button><div class="api-note">Güvenlik için Riot API anahtarını tarayıcıya gömme. Üretimde sunucu tarafında <code>/api/player</code> proxy endpoint’i oluştur.</div></form><div class="stat-panel"><p class="eyebrow">Entegrasyon alanı</p><h3>Verilerin burada görünecek.</h3><p style="color:var(--muted)">Gerçek API bağlantısı kurulmadığı için sahte istatistik göstermiyoruz. Form; Riot ID ve tagline değerlerini backend’e göndermeye hazırdır.</p><div class="feature-grid" style="grid-template-columns:repeat(2,1fr);margin-top:25px"><div class="feature-card"><span class="feature-index">API // 01</span><h3>Kimlik doğrulama</h3><p>Sunucu tarafında güvenli anahtar yönetimi.</p></div><div class="feature-card"><span class="feature-index">API // 02</span><h3>Yanıt modeli</h3><p>Rank, MMR, maç geçmişi ve ajan performansı.</p></div></div></div></div>`)}
function aboutPage(){return layout('Hakkında','VANTA, VALORANT atmosferinden ilham alan bağımsız bir arayüz konseptidir.',`<div class="stat-panel"><p>Bu proje Riot Games’in resmi sitesi değildir ve Riot Games logolarını veya resmi görsellerini kullanmaz. Marka isimleri ilgili sahiplerinin mülkiyetindedir.</p><p style="color:var(--muted)">Amaç; modern, hızlı ve responsive bir bilgi deneyimini; sade veri modelleri, erişilebilir bileşenler ve gereksiz kütüphaneler olmadan sunmaktır.</p></div>`)}
function notFound(){return `<section class="not-found container"><p class="eyebrow">ERROR // 404</p><h1>BU SAYFA KAYIP.</h1><p style="color:var(--muted)">Aradığın rota bulunamadı.</p><a class="button primary" href="#/">Ana sayfaya dön</a></section>`}
function openAgent(name){const a=agents.find(x=>x.name===name);$('#modal-root').innerHTML=`<div class="modal-backdrop"><article class="modal"><button class="modal-close" aria-label="Kapat">×</button><span class="role">${a.role}</span><h2>${a.name}</h2><p style="color:var(--muted)">${a.desc}</p>${a.abilities.map(x=>`<div class="ability"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</article></div>`;$('.modal-close').onclick=()=>$('#modal-root').innerHTML='';$('.modal-backdrop').onclick=e=>{if(e.target.classList.contains('modal-backdrop'))$('#modal-root').innerHTML=''}}
function bind(){document.querySelectorAll('[data-route-link]').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===location.hash));document.querySelectorAll('.data-card[data-agent]').forEach(c=>c.onclick=()=>openAgent(c.dataset.agent));const as=$('#agent-search');if(as){let role='ALL';const render=()=>{const q=as.value.toLowerCase();$('#agent-grid').innerHTML=agentCards(agents.filter(a=>(role==='ALL'||a.role===role)&&a.name.toLowerCase().includes(q)))};as.oninput=render;document.querySelectorAll('[data-role]').forEach(b=>b.onclick=()=>{role=b.dataset.role;document.querySelectorAll('[data-role]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()})}const ws=$('#weapon-search');if(ws){const wf=$('#weapon-filter');const render=()=>$('#weapon-grid').innerHTML=weaponCards(weapons.filter(w=>(wf.value==='ALL'||w.category===wf.value)&&w.name.toLowerCase().includes(ws.value.toLowerCase())));ws.oninput=render;wf.onchange=render}const form=$('#stats-form');if(form)form.onsubmit=e=>{e.preventDefault();alert('API endpoint hazır değil. Gerçek veri göstermek için backend bağlantısını tamamlayın.')}}
function render(){const route=location.hash.replace('#/','').split('/')[0];const pages={agents:agentsPage,weapons:weaponsPage,maps:mapsPage,stats:statsPage,about:aboutPage};app.innerHTML=route?pages[route]?pages[route]():notFound():home();bind();window.scrollTo(0,0)}
$('#theme-toggle').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='light'?'':'light';localStorage.setItem('vanta-theme',document.documentElement.dataset.theme)};if(localStorage.getItem('vanta-theme'))document.documentElement.dataset.theme='light';$('.nav-toggle').onclick=()=>{$('.nav-menu').classList.toggle('open');$('.nav-toggle').setAttribute('aria-expanded',$('.nav-menu').classList.contains('open'))};window.addEventListener('hashchange',()=>{$('.nav-menu').classList.remove('open');render()});window.addEventListener('load',()=>{setTimeout(()=>$('#loader').classList.add('done'),450);render()});
