const tacticalAgents = [
  ['Jett','DUELIST','Hızlı giriş, smoke ile görüş kesme ve Tailwind ile güvenli çıkış.'],['Phoenix','DUELIST','Flash ve duvarıyla site girişini aç; ultiyle risksiz bilgi topla.'],['Raze','DUELIST','Boom Bot ile köşeleri temizle, patlayıcılarla rakibi açık alana zorla.'],['Reyna','DUELIST','İlk kill sonrası Devour/Dismiss ile avantajı koru; gereksiz düellodan kaçın.'],['Yoru','DUELIST','Fake teleport ve flash ile savunmayı böl; Gatecrash çıkışını önceden planla.'],['Neon','DUELIST','Duvarla görüşü kesip hızlı koşu ile alan aç; takımın trade mesafesinde olsun.'],['Iso','DUELIST','Double Tap kalkanıyla ilk teması al; Contingency ile güvenli giriş oluştur.'],['Waylay','DUELIST','Hareket yetenekleriyle açıları boz; takımın giriş zamanını hızlandır.'],
  ['Brimstone','CONTROLLER','Smoke’ları giriş ve retake zamanına sakla; Stim Beacon ile takım push’unu güçlendir.'],['Viper','CONTROLLER','Zehir duvarını bölgeyi bölecek şekilde kur; yakıtı spike planına göre yönet.'],['Omen','CONTROLLER','Dark Cover ile açı kapat, Paranoia ile site girişini kolaylaştır ve teleport ile şaşırt.'],['Astra','CONTROLLER','Yıldızlarını erken tüketme; Gravity Well ve Nova Pulse’u rakip push’una sakla.'],['Harbor','CONTROLLER','Cove ile spike kurulumunu koru, Cascade ile takımına güvenli geçiş aç.'],['Clove','CONTROLLER','Ölümden sonra bile smoke desteği ver; takımın trade planından kopma.'],['Miks','CONTROLLER','Alan kontrolü ve takım desteğini eşleştir; rotasyonları rakibe pahalı hale getir.'],
  ['Sova','INITIATOR','Recon Bolt ile bilgi al, Shock Bolt ile rakibi pozisyonundan çıkar; drone ile giriş hazırla.'],['Breach','INITIATOR','Duvar arkasından stun ve flash gönder; takımın girişinden hemen önce yetenek kullan.'],['Skye','INITIATOR','Guiding Light ile açı kontrol et, Trailblazer ile takımına güvenli bilgi sağla.'],['KAY/O','INITIATOR','ZERO/POINT ile rakip yeteneklerini bastır; FRAG/MENT ile dar alanı temizle.'],['Fade','INITIATOR','Haunt ve Prowler ile iz sür; Seize’i rakibin kaçış rotasına yerleştir.'],['Gekko','INITIATOR','Dizzy ile giriş bilgisi al; Wingman’i spike kurma veya çözme için doğru anda gönder.'],['Tejo','INITIATOR','Uzaktan patlayıcılarla savunmayı dağıt; takım push’undan önce kritik alanı boşalt.'],
  ['Sage','SENTINEL','Barrier Orb ile rotayı böl, Slow Orb ile spike alanını geciktir; heal’i trade sonrası kullan.'],['Cypher','SENTINEL','Tripwire’ları flank rotalarına kur, kamera bilgisiyle takım rotasyonunu yönet.'],['Killjoy','SENTINEL','Alarm Bot ve Turret ile arkanı güvenceye al; Lockdown ile site kontrolü kur.'],['Chamber','SENTINEL','Trademark ile flank’i izle, Headhunter ile uzun açı tut; Rendezvous çıkışını güvenli kur.'],['Deadlock','SENTINEL','Sonic Sensor ile sesli hareketleri takip et, GravNet ile girişleri yavaşlat.'],['Vyse','SENTINEL','Shear ile geçişleri kapat, Arc Rose ile kritik açıyı kör ederek rakibi ayır.'],['Veto','SENTINEL','Rakip yeteneklerini etkisizleştirerek takımının tercih ettiği alanı koru.']
];

const tacticalWeapons = [
  ['Classic','TABANCA','Ücretsiz','Ekonomi round’unda yakın mesafede sağ tık, orta mesafede kontrollü sol tık kullan.'],['Shorty','TABANCA','300','Dar köşe ve smoke pusularında kullan; açık alanda uzun duel alma.'],['Frenzy','TABANCA','450','Yakın mesafe hızlı baskı için hareketli oyna; mermi kontrolünü koru.'],['Ghost','TABANCA','500','Sessiz tekli atışlarla kafa hizasını koru; gereksiz spray yapma.'],['Sheriff','TABANCA','800','Tek atış disiplinini kullan; rakip avantajlıysa çatışmayı zorlamadan geri çekil.'],['Bandit','TABANCA','600','Ekonomik round’larda orta mesafe açıları tut ve takımınla trade oyna.'],
  ['Stinger','SMG','1.100','Yakın mesafede kısa spray ve hareket kullan; uzun koridorlardan kaçın.'],['Spectre','SMG','1.600','Smoke içi çatışmalarda ve yakın-orta mesafede kontrollü spray kullan.'],['Bulldog','TÜFEK','2.050','Ekonomi avantajı için burst modunu uzun açılarda, otomatiği yakın mesafede kullan.'],['Guardian','TÜFEK','2.250','Uzun açılarda tekli atışla oyna; rakibe gereksiz yakınlaşma.'],['Phantom','TÜFEK','2.900','Smoke içi çatışmalarda ve yakın-orta mesafede kontrollü spray kullan.'],['Vandal','TÜFEK','2.900','Uzun açılarda tekli atış kullan; spray yerine kısa burst tercih et.'],
  ['Bucky','SHOTGUN','850','Köşe ve dar alan savunmasında bekle; açık alanda mesafe dezavantajını unutma.'],['Judge','SHOTGUN','1.850','Hızlı site baskısı veya dar savunma için kullan; her atış sonrası konum değiştir.'],['Marshal','SNIPER','950','İlk teması alıp geri düş; hafif zırhlı rakiplere karşı ekonomi değerini kullan.'],['Operator','SNIPER','4.700','İlk teması alıp hemen pozisyon değiştir; yalnız peek atma.'],['Ares','AĞIR','1.600','Duvar arkası baskı ve dar geçitlerde kullan; hareket ederken spray’i kontrol et.'],['Odin','AĞIR','3.200','Duvar arkası baskı ve dar geçit kontrolünde takım bilgisiyle kullan.'],['Bıçak','YAKIN DÖVÜŞ','Ücretsiz','Hızlı rotasyon ve sessiz hareket için kullan; gereksiz risk alma.'],['Warden','ÖZEL','2.900','Özel ekipman olarak taktik planına dahil et; takımın alan kontrolüyle birlikte kullan.']
];

function tacticsPage() {
  const style = `<style>
    .tactics-hero{padding:145px 0 45px;background:radial-gradient(circle at 85% 20%,rgba(255,70,85,.2),transparent 30%),var(--bg-2)}
    .tactics-tabs{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:35px 0}.tactics-tab{border:1px solid var(--line);background:var(--panel);color:var(--ink);padding:25px;text-align:left;cursor:pointer;transition:.25s}.tactics-tab strong{display:block;font:800 34px "Barlow Condensed";text-transform:uppercase}.tactics-tab span{display:block;color:var(--muted);font-size:13px;margin-top:5px}.tactics-tab.active,.tactics-tab:hover{border-color:var(--red);background:linear-gradient(135deg,rgba(255,70,85,.16),var(--panel))}.tactics-layout{display:grid;grid-template-columns:300px 1fr;gap:18px}.tactics-picker{border:1px solid var(--line);background:var(--panel);padding:16px;height:max-content;position:sticky;top:95px;max-height:calc(100vh - 120px);overflow:auto}.tactics-picker h3{font:800 23px "Barlow Condensed";text-transform:uppercase;margin:0 0 12px}.tactic-choice{display:flex;align-items:center;gap:10px;width:100%;padding:12px;border:1px solid transparent;background:transparent;color:var(--ink);text-align:left}.tactic-choice:hover,.tactic-choice.active{border-color:var(--red);background:rgba(255,70,85,.1)}.tactic-choice b{display:grid;place-items:center;width:32px;height:32px;flex:none;background:var(--red);color:#fff;font:800 18px "Barlow Condensed"}.tactic-choice small{display:block;color:var(--muted);font-size:10px;margin-top:2px}.tactic-result{border:1px solid var(--line);background:var(--panel);padding:30px;min-height:360px}.tactic-result h2{font:800 58px "Barlow Condensed";text-transform:uppercase;margin:5px 0}.tactic-result>p{color:var(--muted);max-width:650px}.tactic-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:28px}.tactic-step{border-top:2px solid var(--red);padding:14px 0}.tactic-step b{color:var(--red);font:800 13px "Barlow Condensed";letter-spacing:.12em}.tactic-step p{color:var(--muted);font-size:13px;margin:7px 0 0}.tactics-note{margin-top:18px;color:var(--muted);font-size:12px;border-left:3px solid var(--red);padding-left:12px}@media(max-width:700px){.tactics-tabs,.tactics-layout,.tactic-steps{grid-template-columns:1fr}.tactics-picker{position:static;max-height:none}.tactics-hero{padding-top:120px}.tactic-result h2{font-size:45px}}
  </style>`;
  const mode = window.tacticsMode || 'agents';
  const selected = window.tacticsSelected || 0;
  const list = mode === 'agents' ? tacticalAgents : tacticalWeapons;
  const item = list[selected] || list[0];
  const isAgent = mode === 'agents';
  const choices = list.map((x,i) => `<button class="tactic-choice ${i === selected ? 'active' : ''}" data-tactic-index="${i}"><b>${x[0][0]}</b><span>${x[0]}<small>${x[1]}</small></span></button>`).join('');
  return `${style}<section class="tactics-hero"><div class="container"><p class="eyebrow">VANTA // TAKTİK LABORATUVARI</p><h1 class="page-head"><span style="font:800 clamp(42px,6vw,78px)/.9 'Barlow Condensed';text-transform:uppercase">KAZANMAK İÇİN<br>PLAN YAP.</span></h1><p style="color:var(--muted);max-width:610px">Tüm savaşçıları ve silahları seç. Ardından seçimine özel hazırlanmış kullanım planını ve kazanma yaklaşımını incele.</p><div class="tactics-tabs"><button class="tactics-tab ${isAgent?'active':''}" data-tactic-mode="agents"><strong>⚔ SAVAŞÇILAR (${tacticalAgents.length})</strong><span>Ajan seç, yeteneklerini stratejiye dönüştür.</span></button><button class="tactics-tab ${!isAgent?'active':''}" data-tactic-mode="weapons"><strong>◈ SİLAHLAR (${tacticalWeapons.length})</strong><span>Silah seç, mesafe ve ekonomi planını kur.</span></button></div></div></section><section class="page" style="padding-top:35px"><div class="container"><div class="tactics-layout"><aside class="tactics-picker"><h3>${isAgent?'Tüm savaşçılar':'Tüm silahlar'}</h3>${choices}</aside><article class="tactic-result"><span class="role">${item[1]}</span><h2>${item[0]}</h2><p>${item[2]}</p><div class="tactic-steps"><div class="tactic-step"><b>01 // HAZIRLIK</b><p>${isAgent?'Yeteneklerini round öncesi takım planına bağla; bilgi ve trade bekle.':'Ekonomiyi ve mesafeyi kontrol et. Silahın güçlü olduğu açıları takımınla paylaş.'}</p></div><div class="tactic-step"><b>02 // UYGULAMA</b><p>${isAgent?'İlk temastan sonra aynı açıya dönme; yetenek kullanıp avantajlı pozisyona geç.':'Nişan hizasını koru, gereksiz reload yapma ve round hedefini koru.'}</p></div><div class="tactic-step"><b>03 // KAZANÇ</b><p>${isAgent?'Alanı kazanınca spike ve rotasyon bilgisini takımına aktar.':'Mermiyi değil zamanı değerlendir; avantajı koru ve trade mesafesinde oyna.'}</p></div></div><p class="tactics-note">Bu öneri genel bir oyun rehberidir; harita, ekonomi ve takım kompozisyonuna göre uyarlayın.</p></article></div></div></section>`;
}

function bindTactics() {
  document.querySelectorAll('[data-tactic-mode]').forEach(button => button.onclick = () => { window.tacticsMode = button.dataset.tacticMode; window.tacticsSelected = 0; window.render(); });
  document.querySelectorAll('[data-tactic-index]').forEach(button => button.onclick = () => { window.tacticsSelected = Number(button.dataset.tacticIndex); window.render(); });
}
window.addEventListener('load', () => { if (location.hash.replace('#/','').split('/')[0] === 'tactics') { window.render(); } });
window.addEventListener('hashchange', () => { if (location.hash.replace('#/','').split('/')[0] === 'tactics') { window.render(); } });
